### ISSUE TITLE
start leader game search - cancel game search - join game - crash

### ISSUE THREAD

**Issue by foodlfg** [FAForever/client#1007]
--
Client crashes after canceling a leader game search then trying to join to a lobby.

System details:
Linux Ubuntu Gnome 16.04 LTS
Client versions: 0.16.0, 0.16.1

--
Under Play/1vs1 Automatch/
Click on "Play!" 
Click on "Stop Play"
Try to join to a lobby
Client crashes

--
It should not crash because it's a basic feature.
Please don't tell me that I should use the client version 0.16.1 because that one has this problem too for me (i've tried). I'm still using 0.16.0 because I've modified the look of the client because I had "font too large" issues with it...

--
Crash Log
```
Traceback (most recent call last):
  File "/home/XX/Games/fafclient/client-0.16.0/src/games/_gameswidget.py", line 356, in gameDoubleClicked
    self.client.join_game(uid=game.uid)
  File "/home/XX/Games/fafclient/client-0.16.0/src/client/_clientwindow.py", line 1208, in join_game
    self.game_session.listen()
  **File "/home/XX/Games/fafclient/client-0.16.0/src/fa/game_session.py", line 89, in listen
    assert self.state == GameSessionState.OFF
AssertionError**

Runtime info:

FAF Username: foodlfg
FAF Version: 0.16.0
FAF Environment: production
FAF Directory: /home/XX/FAForever
FA Path: : /home/XX/PlayOnLinux's virtual drives/supCom/drive_c/Program Files (x86)/Steam/steamapps/common/Supreme Commander Forged Alliance
Home Directory: /home/XX/Documents
Platform: Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
Uname: uname_result(system='Linux', node='pc1', release='4.13.0-36-generic', version='#40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018', machine='x86_64', processor='x86_64')
```

Thanks!

**Comment by Wesmania** [comment]
I know of this one. I intend to refactor game launching code soon so it hopefully gets fixed.
