### ISSUE TITLE
Error when trying to upload a mod in the vault

### ISSUE THREAD

**Issue by ppipp** [FAForever/client#154]
**FAF Username:** pip

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** D:\Games\Steam\steamapps\common\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\pip\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "modvault__init__.pyc", line 225, in openUploadForm
  File "modvault\uploadwidget.pyc", line 59, in **init**
  File "modvault\uploadwidget.pyc", line 182, in updateThumbnail
NameError: global name 'logger' is not defined

}}}

**Comment by Wesmania** [comment]
Once we reintroduce map uploads, it will be through the new api, so this bug is obsolete.
