### ISSUE TITLE
patch fail

### ISSUE THREAD

**Issue by thetrav** [FAForever/client#176]
opened FAF (first time in a while) double clicked Forged Alliance Forever to start custom game, patching began, got: 
```
**FAF Username:** thetrav

**FAF Version:** 0.10.122

**FAF Directory:** C:\users\Public\FAForever

**FA Path:** C:/Steam/SteamApps/common/Supreme Commander Forged Alliance

**Home Directory:** C:\users\thetrav\My Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\users\\Public\\FAForever\\cache\\patchedFile'

}}}
```
clicked continue got:
```
Update started at 2015-02-15 10:25:56
Using game path: C:/Steam/SteamApps/common/Supreme Commander Forged Alliance
Using appdata: C:\users\Public\FAForever
Connected to update server at 2015-02-15 10:25:57
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(UPDATE, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9])
writeToServer(UPDATE, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26])
writeToServer(UPDATE, [bin, init_faf.lua, e1fede1183ca3f06bb6031fdc93823b3])
writeToServer(UPDATE, [bin, ForgedAlliance.exe, d04c376ef5d9e7a3cf99f4dbe4b0bb12])
writeToServer(UPDATE, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e])
writeToServer(UPDATE, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1])
writeToServer(UPDATE, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(SEND_PATCH_URL) - 232 bytes
bin/init_faf.lua is patched.
handleAction(SEND_PATCH_URL) - 274 bytes
bin/ForgedAlliance.exe is patched.
handleAction(UP_TO_DATE) - 64 bytes
file : SupComDataPath.lua
SupComDataPath.lua is up to date.
handleAction(UP_TO_DATE) - 70 bytes
file : SupComDataPathFAF.lua
SupComDataPathFAF.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : init_ladder1v1.lua
init_ladder1v1.lua is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [FAFGAMEDATA])
handleAction(LIST_FILES_TO_UP) - 352 bytes
Files to update: [faforever.faf, effects.nx2, env.nx2, loc.nx2, lua.nx2, meshes.nx2, modules.nx2, projectiles.nx2, schook.nx2, textures.nx2, units.nx2]
writeToServer(UPDATE, [gamedata, schook.nx2, 40d5c5fe016b2eafefc2b759172806c9])
writeToServer(UPDATE, [gamedata, effects.nx2, df11b1cc8eeaed0e21fa5b023228300c])
writeToServer(UPDATE, [gamedata, modules.nx2, 3e7600e6683c9d3ebfca2829f03e6d22])
writeToServer(UPDATE, [gamedata, lua.nx2, 6ff850d1daa9dce6579a8972d40a6bfd])
writeToServer(UPDATE, [gamedata, textures.nx2, f71b926d88a6116897e8dd9fe15ddb46])
writeToServer(UPDATE, [gamedata, env.nx2, 59c0e86ba51b94a4e9e3cf03408a4a4f])
writeToServer(UPDATE, [gamedata, meshes.nx2, b1e06cea9edacc87c7a57e01a179a021])
writeToServer(UPDATE, [gamedata, faforever.faf, 51c196294638c22071dc8ee01e55771e])
writeToServer(UPDATE, [gamedata, loc.nx2, 29677357909716a89901b40a0eca7b2c])
writeToServer(UPDATE, [gamedata, projectiles.nx2, 9ee2c8d1892b104ff2c95685aa6cb3fb])
writeToServer(UPDATE, [gamedata, units.nx2, 0cd14d4fe6fb78603f8ef0148af991d0])
handleAction(SEND_PATCH_URL) - 244 bytes
gamedata/schook.nx2 is patched.
handleAction(SEND_PATCH_URL) - 250 bytes
gamedata/effects.nx2 is patched.
handleAction(SEND_PATCH_URL) - 250 bytes
gamedata/modules.nx2 is patched.
handleAction(SEND_PATCH_URL) - 226 bytes
gamedata/lua.nx2 is patched.
handleAction(SEND_PATCH_URL) - 256 bytes
gamedata/textures.nx2 is patched.
handleAction(SEND_PATCH_URL) - 226 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-02-15 10:27:52
```

**Comment by thetrav** [comment]
Trying again worked without error.  So the issue is around the error messaging.  
Networks are expected to fail, something friendlier should be shown to user with a retry button

**Comment by simshadows** [comment]
Doesn't seem to work for me, even after some 5 or so tries.

```

**FAF Username:** DOOMSPECTRE

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** E:\Games\Steam Games\steamapps\common\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\Rhomil Cabanilla\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

```

Continue gives me:

```
Update started at 2015-07-19 13:21:11
Using game path: E:\Games\Steam Games\steamapps\common\Supreme Commander Forged Alliance
Using appdata: C:\ProgramData\FAForever
Connected to update server at 2015-07-19 13:21:11
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(UPDATE, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9])
writeToServer(UPDATE, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26])
writeToServer(UPDATE, [bin, init_faf.lua, 83a9d5157d1c25a61add0dc68d3ba516])
writeToServer(UPDATE, [bin, ForgedAlliance.exe, 68ca8130ec2fa999bf6840c82dc2fff8])
writeToServer(UPDATE, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e])
writeToServer(UPDATE, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1])
writeToServer(UPDATE, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : init_faf.lua
init_faf.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : ForgedAlliance.exe
ForgedAlliance.exe is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : SupComDataPath.lua
SupComDataPath.lua is up to date.
handleAction(UP_TO_DATE) - 70 bytes
file : SupComDataPathFAF.lua
SupComDataPathFAF.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : init_ladder1v1.lua
init_ladder1v1.lua is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [FAFGAMEDATA])
handleAction(LIST_FILES_TO_UP) - 352 bytes
Files to update: [faforever.faf, effects.nx2, env.nx2, loc.nx2, lua.nx2, meshes.nx2, modules.nx2, projectiles.nx2, schook.nx2, textures.nx2, units.nx2]
writeToServer(UPDATE, [gamedata, schook.nx2, bdf517e78380e4237abc5709c3959efd])
writeToServer(UPDATE, [gamedata, effects.nx2, 852d8f1edb69b0f8b1eeaeff8a425655])
writeToServer(UPDATE, [gamedata, modules.nx2, f49d3cf00677b1ece7ef354e26d0398b])
writeToServer(UPDATE, [gamedata, lua.nx2, 0e38f6686dd0abab0e7b8ec919217b71])
writeToServer(UPDATE, [gamedata, textures.nx2, 8ec134fe0eb12f0a81d4d8af82262b17])
writeToServer(UPDATE, [gamedata, env.nx2, 90b316f705bf49ff7416a8b5cabc7b6d])
writeToServer(UPDATE, [gamedata, meshes.nx2, 2cf16b2c841bca53122c7efd3949b691])
writeToServer(UPDATE, [gamedata, faforever.faf, 51c196294638c22071dc8ee01e55771e])
writeToServer(UPDATE, [gamedata, loc.nx2, 645f7f71b46ec5d500f19e05ed055fdb])
writeToServer(UPDATE, [gamedata, projectiles.nx2, f3bdd4171255fd71fdefbf1d7bf0cffb])
writeToServer(UPDATE, [gamedata, units.nx2, 12e503abc65889b320d63e340d708fd3])
handleAction(UP_TO_DATE) - 48 bytes
file : schook.nx2
schook.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : effects.nx2
effects.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : modules.nx2
modules.nx2 is up to date.
handleAction(SEND_PATCH_URL) - 226 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-07-19 13:22:19
```
