### ISSUE TITLE
Opening a replay in Vault fails

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#179]
**FAF Username:** Downlord

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Games\Supreme Commander - Forged Alliance

**Home Directory:** C:\Users\Downlord\Documents

**Stacktrace:**
{{{
    Traceback (most recent call last):
      File "replays\_replayswidget.pyc", line 121, in finishRequest
      File "fa\exe.pyc", line 150, in replay
      File "json\__init__.pyc", line 338, in loads
      File "json\decoder.pyc", line 366, in decode
      File "json\decoder.pyc", line 384, in raw_decode
    ValueError: No JSON object could be decoded
}}}

**Comment by micheljung** [comment]
Hmm it seems this only happens with live replays and a short while after the game has finished.

**Comment by IDragonfire** [comment]
The last time I debugged this that was a server cache problem.
Instead of sending a replay you receive nothing or a 0-byte stream/file.
Try it again after a while solved the problem.

**Comment by micheljung** [comment]
wrong receiver ;)

2015-04-03 14:51 GMT+02:00 IDragonfire <notifications@github.com>:

**Comment by Sheeo** [comment]
Happens when replays are corrupted serverside -- we should fix the error message, of course.
