### ISSUE TITLE
Game "pauses"

### ISSUE THREAD

**Issue by Mrzcion** [FAForever/client#204]
the game pauses, with NO indication of who is lagging/behind data.
and even if all players but one leaves it still stays paused.

**FAF Username:** MrZcion

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\mark\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 366, in decode
  File "json\decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by Sheeo** [comment]
Hey Zcion,

This isn't an issue with the client. Can you post a replay or game id [here](https://github.com/FAForever/fa/issues/new) instead?

**Comment by Mrzcion** [comment]
Det er gjort

MvhMark Newton

Date: Mon, 13 Apr 2015 12:28:16 -0700
