### ISSUE TITLE
FAF Crash during patch update

### ISSUE THREAD

**Issue by FC-NoHeroes** [FAForever/client#213]
Im not quite sure what happened. last night the game did it's update. this morning there was another update waiting and when it installed it crashed. Here is the log.

**FAF Username:** FC-NoHeroes

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\Smoothknight\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by usling** [comment]
i get this as well.



**FAF Username:** usling

**FAF Version:** 0.10.122

**FAF Directory:** C:\users\Public\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\users\usling\My Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 706, in applyPatch
  File "subprocess.pyc", line 522, in call
  File "subprocess.pyc", line 702, in __init__
  File "subprocess.pyc", line 857, in _get_handles
WindowsError: [Error 0] Success

}}}




I play via Wine in Linux, i don't expect much support.

**Comment by usling** [comment]
When trying to join a game, it wants to update itself. I get this error message (it varies as you can see from my previous comment above):

**FAF Username:** usling

**FAF Version:** 0.10.122

**FAF Directory:** C:\users\Public\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\users\usling\My Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 706, in applyPatch
  File "subprocess.pyc", line 522, in call
  File "subprocess.pyc", line 702, in __init__
  File "subprocess.pyc", line 857, in _get_handles
WindowsError: [Error 0] Success

}}}


----------------------------------------  after i press continue: -------------------------------------
"Sorry, Forged Alliance couldn't complete the upgrade!" etc


Update started at 2015-07-13 18:27:16
Using game path: C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance
Using appdata: C:\users\Public\FAForever
Connected to update server at 2015-07-13 18:27:16
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(UPDATE, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9])
writeToServer(UPDATE, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26])
writeToServer(UPDATE, [bin, init_faf.lua, f7e666f342d17e3829fc19dbc140e4c5])
writeToServer(UPDATE, [bin, ForgedAlliance.exe, dcf82138bb46628d99861c64d21407b7])
writeToServer(UPDATE, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e])
writeToServer(UPDATE, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1])
writeToServer(UPDATE, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : init_faf.lua
init_faf.lua is up to date.
handleAction(SEND_PATCH_URL) - 274 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-07-13 18:27:36

**Comment by bz2king** [comment]
**FAF Username:** Blitzenkrieger

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\Nate\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Diasberk** [comment]
**FAF Username:** XelNaga

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\THQ\Gas Powered Games\Supreme Commander - Forged Alliance

**Home Directory:** C:\ProgramData\FAForever\user

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 13] Permission denied: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment]
To everyone here: Try clearing your gamedata and cache folders. This problem stems from permission issues when you run the client as administrator and then stop doing so.
