### ISSUE TITLE
COOP Replays crash updater

### ISSUE THREAD

**Issue by Jabokoe** [FAForever/client#216]
**FAF Username:** Jabokoe
**FAF Version:** 0.10.125
**FAF Directory:** C:\ProgramData\FAForever
**FA Path:** D:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance
**Home Directory:** S:\Users\Jaber\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}
**What I was doing:**
Clicked a replay for Black Day COOP mission in Duo Leader Board. Updater starts as I expected. Takes a bit longer than usual and then crashes.
First time choosing continue spits out a stacktrace. Recklicking the replay and retrying continue makes it stuck on Updating load bar forever.
**Error Details:**
As for the missing file/directory. The only directory that showed up in C:\ProgramData\FAForever\cache is an empty 'galacticwar' folder (I never participated in those tests). Though there is a file called 'temp.patch' there, maybe it needs that instead? Also the second stacktrace after clicking continue reads as follows
```
Update started at 2015-07-31 14:08:02
Using game path: D:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance
Using appdata: C:\ProgramData\FAForever
Connected to update server at 2015-07-31 14:08:02
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(PATCH_TO, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9, 3634])
writeToServer(PATCH_TO, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26, 3634])
writeToServer(PATCH_TO, [bin, init_faf.lua, e1fede1183ca3f06bb6031fdc93823b3, 3634])
writeToServer(PATCH_TO, [bin, ForgedAlliance.exe, 0ed4a1e0a25939ef964e1cfb6c7e14b6, 3634])
writeToServer(PATCH_TO, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e, 3634])
writeToServer(PATCH_TO, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1, 3634])
writeToServer(PATCH_TO, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe, 3634])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : init_faf.lua
init_faf.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : ForgedAlliance.exe
ForgedAlliance.exe is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : SupComDataPath.lua
SupComDataPath.lua is up to date.
handleAction(UP_TO_DATE) - 70 bytes
file : SupComDataPathFAF.lua
SupComDataPathFAF.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : init_ladder1v1.lua
init_ladder1v1.lua is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [FAFGAMEDATA])
handleAction(LIST_FILES_TO_UP) - 352 bytes
Files to update: [faforever.faf, effects.nx2, env.nx2, loc.nx2, lua.nx2, meshes.nx2, modules.nx2, projectiles.nx2, schook.nx2, textures.nx2, units.nx2]
writeToServer(PATCH_TO, [gamedata, schook.nx2, 42c3bb0fa444e39cf87890b9deed4714, 3634])
writeToServer(PATCH_TO, [gamedata, effects.nx2, 5ad6bdd874143757670666cb8069509d, 3634])
writeToServer(PATCH_TO, [gamedata, modules.nx2, b8e17a87bc7ee3aee43a6e67a7032320, 3634])
writeToServer(PATCH_TO, [gamedata, lua.nx2, d6cd409e8fad4563e47b446cca1eb9c4, 3634])
writeToServer(PATCH_TO, [gamedata, textures.nx2, aa24a6c1f7588a69921403465c75b868, 3634])
writeToServer(PATCH_TO, [gamedata, env.nx2, 25d0a20db863cb7b1a578e543a375ee3, 3634])
writeToServer(PATCH_TO, [gamedata, meshes.nx2, 2cf16b2c841bca53122c7efd3949b691, 3634])
writeToServer(PATCH_TO, [gamedata, faforever.faf, 51c196294638c22071dc8ee01e55771e, 3634])
writeToServer(PATCH_TO, [gamedata, loc.nx2, 403232c8a11125057410c84b11af1618, 3634])
writeToServer(PATCH_TO, [gamedata, projectiles.nx2, f3bdd4171255fd71fdefbf1d7bf0cffb, 3634])
writeToServer(PATCH_TO, [gamedata, units.nx2, 7c98ee73e76a2e972cb466b8b6a37749, 3634])
handleAction(UP_TO_DATE) - 48 bytes
file : schook.nx2
schook.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : effects.nx2
effects.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : modules.nx2
modules.nx2 is up to date.
handleAction(SEND_PATCH_URL) - 226 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-07-31 14:08:23
```

**Comment by Sheeo** [comment]
Clear your gamedata -- your client has a shortcut for doing this in the tooltip menu.

**Comment by Jabokoe** [comment]
Just wanted to add that this fixed itself (before your reply) by trying to host co-op for the same scenario as the replay I wanted to watch. 
Seems that it got all the files without having to clear game data, or reinstall by deleting folders. Might be usefull for other troubleshooting.
(Due to vacation I kept forgetting to reply to this.)
