### ISSUE TITLE
PLz help

### ISSUE THREAD

**Issue by longshot1** [FAForever/client#217]
Ive been getting these errors as of lately co op and multiplayer please help what should do? :+1: 

**FAF Username:** Longshot

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\Trevor and nat\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment]
Clear your gamedata -- your client has a shortcut for doing this in the tooltip menu.
