### ISSUE TITLE
Map / Replay Load Error

### ISSUE THREAD

**Issue by Silent56** [FAForever/client#218]
**FAF Username:** Silent56

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** E:\Steam\SteamApps\common\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\BrendanC\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

Went to the replay page in the launcher and selected the 1v1 replay but it gave an error.

**Comment by Sheeo** [comment]
This means the map / replay is corrupted serverside, unfortunately.
