### ISSUE TITLE
CO-OP Error (14/08/15)

### ISSUE THREAD

**Issue by RockyTurtle** [FAForever/client#224]
I keep getting this error whenever i try to play co-op with a friend:

**Home Directory:** C:\Users\Simon\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by RudeStrudel** [comment]
confirming getting the same exact error here as well


**FAF Username:** phayne

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\Owner\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment]
Clear your gamedata cache. The client provides a utility for doing so in the toolbar. Thanks for reporting!

Relates to #225
