### ISSUE TITLE
Patcher error

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#225]
{{{
    Traceback (most recent call last):
    File "fa\updater.pyc", line 899, in readDataFromServer
    File "fa\updater.pyc", line 819, in handleAction
    File "fa\updater.pyc", line 707, in applyPatch
    File "shutil.pyc", line 119, in copy
    File "shutil.pyc", line 82, in copyfile
    IOError: [Errno 2] No such file or directory: 'C:\ProgramData\FAForever\cache\patchedFile'

    }}}

Happens sometimes with the current patcher.

**Comment by CrazyDutchReaper** [comment]
"Happens sometimes with the current patcher"

**Comment by Sheeo** [comment]
I've cleared the serverside patch cache. Can you still reproduce?

**Comment by CrazyDutchReaper** [comment]
As far as i am aware, it does.

**Comment by arkitect-dev** [comment]
@Sheeo is there anything further that needs to be done to the patcher or can this be closed?

**Comment by Sheeo** [comment]
Yes plenty of things to be done to the current patcher. The issue is sufficiently nondescript that it does not really serve a purpose though, so let's close.
