### ISSUE TITLE
Clicked on replay in lobby vault, then this happened.

### ISSUE THREAD

**Issue by mirroredwang** [FAForever/client#231]
**FAF Username:** mirroredwang

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\ven\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by SalvationKing0** [comment]
Looks like I have the same issue, clicked on a replay and this happened.


**FAF Username:** SalvationKing0

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** D:\Personal\Libraries\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by HardlySoftly** [comment]
Fixed in dev branch, thanks for the report though SalvationKing0
