### ISSUE TITLE
error when looking thru vault 

### ISSUE THREAD

**Issue by puffpants** [FAForever/client#235]
**FAF Username:** Wesley

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** D:\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by SwayGin-FAF** [comment]
Seemingly similar problem as well:


**FAF Username:** Swaygin

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\Johnny\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 536, in readDataFromServer
  File "replays\_replayswidget.pyc", line 541, in process
  File "replays\_replayswidget.pyc", line 548, in receiveJSON
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by madformuse** [comment]
Are these errors caused by the relevant server not running? I haven't investigated but I know similar things happened to me and I later found out that there was a problem server side which required a reboot. If that was the case I think a better error would help :)

**Comment by Sheeo** [comment]
These errors happen when the replay serverside is invalid.
