### ISSUE TITLE
Updated to Windows 10 and have permission problems

### ISSUE THREAD

**Issue by rfp313** [FAForever/client#243]
I wanted to clear the cache within the FAF client and I get the following:

**Home Directory:** C:\Users\Pastora family\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "client\_clientwindow.pyc", line 804, in clearCache
  File "util\__init__.pyc", line 194, in clearDirectory
  File "shutil.pyc", line 256, in rmtree
  File "shutil.pyc", line 254, in rmtree
WindowsError: [Error 5] Access is denied: 'C:\\ProgramData\\FAForever\\cache'

}}}

I believe this is a permission problem after getting FAF setup.  Can someone please help me resolve this?

**Comment by Sheeo** [comment]
Something took ownership of the cache directory. You'll need to fix this by modifying the permissions on the directory yourself for now.
