### ISSUE TITLE
TURN: argument 1 has unexpected type 'instance'

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#278]
```
2015-12-23 16:48:14,792 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\connectivity\turn.py", line 194, in refresh
  File "src\connectivity\turn_client.py", line 32, in _write
  File "src\connectivity\turn_client.py", line 129, in send
TypeError: arguments did not match any overloaded call:
  QUdpSocket.writeDatagram(str, QHostAddress, int): argument 1 has unexpected type 'instance'
  QUdpSocket.writeDatagram(QByteArray, QHostAddress, int): argument 1 has unexpected type 'instance'
```

**Comment by Sheeo** [comment]
I do believe this is an ancient, solved problem.
