### ISSUE TITLE
Error loading xdelta3 file

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#282]
Error occurs whenever I try to update FA (by launching it) from the dev lobby on vagrant.

Traceback (most recent call last):
File ".\src\fa\updater.py", line 629, in readDataFromServer
self.handleAction(self.blockSize, action, ins)
File ".\src\fa\updater.py", line 563, in handleAction
self.applyPatch(completePath ,toFile)
File ".\src\fa\updater.py", line 577, in applyPatch
subprocess.call(['xdelta3', '-d','-f', '-s', original, patch, toFile], stdout = subprocess.PIPE)
File "C:\Python27\lib\subprocess.py", line 522, in call
return Popen(popenargs, *kwargs).wait()
File "C:\Python27\lib\subprocess.py", line 710, in init
errread, errwrite)
File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by Sheeo** [comment]
Local environment issue -- `xdelta3.exe` should be somewhere the client can find it.

**Comment by HardlySoftly** [comment]
Are we sure this wouldn't happen in a production lobby though?

I had problems with Microsoft Visual C++ not being installed in Vagrant and that was put down to a local issue.  Only later did a bunch of people have problems after the update.
