### ISSUE TITLE
IRC server messages can crash the client

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#283]
Any message from something that is not in the list of chatters causes a key not found error in src/chat/channel.py

There seems to be an implicit assumption that everything that could send a message is in the list of chatters, although as I found out this doesn't always hold (I got a message from ChanServ in chat).

**Comment by Sheeo** [comment]
Need a stack trace to resolve this

**Comment by HardlySoftly** [comment]
I'd want to understand how the IRC send these messages before I go putting checks before every use of self.chatters[name], since this isn't the only place where this error might occur.

Stack trace:

2016-01-06 06:20:18,903 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\chat\_chatwidget.py", line 93, in poll
    self.once()
  File "src\chat\irclib.py", line 1131, in once
    self.ircobj.process_once()
  File "src\chat\irclib.py", line 215, in process_once
    self.process_data(i)
  File "src\chat\irclib.py", line 184, in process_data
    c.process_data()
  File "src\chat\irclib.py", line 587, in process_data
    self._handle_event(Event(command, prefix, target, [m]))
  File "src\chat\irclib.py", line 610, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "src\chat\irclib.py", line 326, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "src\chat\irclib.py", line 1055, in _dispatcher
    getattr(self, m)(c, e)
  File "src\chat\_chatwidget.py", line 388, in on_privnotice
    self.channels[target].printMsg(source, message)
  File "src\chat\channel.py", line 288, in printMsg
    fmt = Formatters.FORMATTER_MESSAGE_AVATAR if self.chatters[name].avatar else Formatters.FORMATTER_MESSAGE
KeyError: u'ChanServ'
