### ISSUE TITLE
Freeze on joining automatch with upnp

### ISSUE THREAD

**Issue by arkitect-dev** [FAForever/client#314]
I'm hitting an issue when trying to join ladder matches, the game hangs at "setting up automatch"

```
2016-03-06 08:46:41,082 INFO     games._gameswidget             Starting Ranked Search as Factions.UEF, port: 6112
2016-03-06 08:46:41,084 INFO     client._clientwindow           Outgoing JSON Message: {"state": "start", "gameport": 6112, "command": "game_matchmaking", "faction": 1, "mod": "ladder1v1"}
2016-03-06 08:47:17,548 ERROR    client._clientwindow           Not ready for game launch
2016-03-06 08:47:17,549 INFO     client._clientwindow           Handling game_launch via JSON {u'mapname': u'niflheim final', u'args': [u'/numgames 313'], u'command': u'game_launch', u'uid': 4510244, u'mod': u'ladder1v1'}
2016-03-06 08:47:17,549 INFO     fa.check                       Updating FA for map: niflheim final
2016-03-06 08:47:17,549 INFO     fa.check                       Map is available.
2016-03-06 08:47:17,549 INFO     fa.upnp                        UPnP mapping 192.168.178.47:6112
2016-03-06 08:47:17,559 ERROR    fa.upnp                        Exception in UPnP createPortMapping.
Traceback (most recent call last):
  File "src\fa\upnp.py", line 35, in createPortMapping
  File "<COMObject <unknown>>", line 4, in Add
com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024726), None)
```

**Comment by Sheeo** [comment]
`2016-03-06 08:47:17,548 ERROR    client._clientwindow           Not ready for game launch`

Would be the issue here. @Blackclaws wasn't this a non-error, or are we hitting the actual error now?

**Comment by Blackclaws** [comment]
Not ready for game launch last time definitely was a non-error however this seems like a different issue maybe. Client not ready can have 2 reasons. Either connectivity state is set wrong or the game session object is not ready. But with the port mapping error this might actually signalize a real error in connectivity

**Comment by arkitect-dev** [comment]
there weren't any other connectivity issues at the time, but if it is an real connectivity error that would mean problem with upnp outside the clients control? if we can't do anything about that can we detect the problem then abort the game and tell the user there was a upnp problem? hanging indefinitely is bad ux

**Comment by Sheeo** [comment]
Closing this; please reopen with further logging (game.log) if this happens more.
