### ISSUE TITLE
Avatar tool broken for mods

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#321]
Mods unable to give avatars currently, sample log: 

2016-03-30 13:31:22,851 INFO     client._clientwindow           Outgoing JSON Message: {"action": "requestavatars", "command": "admin"}
2016-03-30 13:32:29,532 INFO     client._clientwindow           Outgoing JSON Message: {"action": "add_avatar", "command": "admin", "avatar": "http://content.faforever.com/faf/avatars/cool_riley.png", "user": "Gorton"}
2016-03-30 13:32:29,650 ERROR    client._clientwindow           Error dispatching JSON: {"command": "invalid"}
Traceback (most recent call last):
  File "src\client_clientwindow.py", line 976, in readFromServer
  File "src\client_clientwindow.py", line 1106, in dispatch
  File "src\client_clientwindow.py", line 1132, in handle_invalid
Exception: {u'command': u'invalid'}

**Comment by Sheeo** [comment]
Fixed with database change. Thanks for the report :+1:
