### ISSUE TITLE
If RELEASE-VERSION is lacking, client gets asked to update

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#340]
https://github.com/FAForever/client/pull/338#discussion_r63289944

**Comment by muellni** [comment]
currently you get this exception: 
```fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Error grabbing git version: Command '['git', 'describe', '--tags', '--always']' returned non-zero exit status 128Could not get git version
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sws/projPriv/2017/faf-client/src/__main__.py", line 48, in <module>
    import util
  File "./src/util/__init__.py", line 11, in <module>
    from config import Settings
  File "./src/config/__init__.py", line 135, in <module>
    VERSION = version.get_release_version(fafpath.get_resdir())
  File "./src/config/version.py", line 89, in get_release_version
    raise ValueError("Cannot find the version number! Please provide RELEASE-VERSION file or run from git.")
ValueError: Cannot find the version number! Please provide RELEASE-VERSION file or run from git.
```
which will at least tell you what went wrong.
