### ISSUE TITLE
IO Error while updating "FAF Develop" version of the game

### ISSUE THREAD

**Issue by Justify87** [FAForever/client#422]
I'm getting this error:

2016-09-29 23:49:21,161 ERROR    **main**                       Uncaught exception
Traceback (most recent call last):
  File "src\fa\updater.py", line 655, in readDataFromServer
  File "src\fa\updater.py", line 589, in handleAction
  File "src\fa\updater.py", line 604, in applyPatch
  File "C:\Python27\lib\shutil.py", line 119, in copy
    def copy2(src, dst):
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\ProgramData\FAForever\cache\patchedFile'

**Comment by duk3luk3** [comment]
Could you explain what you mean by "FAF Develop"? That you don't have a normal FAF Lobby Client installed? The updater should maybe be disabled then.

**Comment by Justify87** [comment]
I mean starting a game with this:
![2016_11_07_19_52_55_fa_forever_0 11 60_577](https://cloud.githubusercontent.com/assets/10554299/20071256/007c5176-a524-11e6-9191-cdd68d3d4574.jpg)

However, this was more than a month ago. And the last time I checked I could succesfully launch a "FAF develop" game. (I really think we should name it something else, maybe Alpha or Dev Preview)

**Comment by Wesmania** [comment]
I'll consider this abandoned.
