### ISSUE TITLE
session can be None in uniqueID

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#579]
After getting weird errors, added this debug code:

```
def uniqueID(user, session):
    ''' This is used to uniquely identify a user's machine to prevent smurfing. '''
    if session is None:
        QMessageBox.critical(None, "No session", "Session was not established properly. Please restart FAF.")
        raise "Error"
```

```
2017-01-13 17:52:31,425 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src/client/_clientwindow.py", line 1144, in perform_login
    self.uniqueId = util.uniqueID(self.login, self.session)
  File "src/util/__init__.py", line 586, in uniqueID
    raise "Error"
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

I have no idea how to reproduce it, it seems to happen based on having weird login data presets.

**Comment by duk3luk3** [comment]
It happens every time when logging in before the client has sent the version message to the server, i.e. before the server has actually given the client the session.

**Comment by Wesmania** [comment]
Is it still an issue?

**Comment by Wesmania** [comment]
I'll consider this abandoned.
