### ISSUE TITLE
Encoding nonsense

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#580]
```
2017-01-13 21:14:06,773 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\games\_gameswidget.py", line 313, in hostGameClicked
  File "src\games\hostgamewidget.py", line 62, in __init__
  File "src\fa\maps.py", line 107, in getDisplayName
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 34: ordinal not in range(128)
```

```
2017-01-13 21:19:06,964 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\games\_gameswidget.py", line 294, in gameDoubleClicked
  File "src\fa\check.py", line 86, in check
  File "src\fa\updater.py", line 183, in run
  File "src\fa\updater.py", line 434, in doUpdate
  File "src\fa\updater.py", line 74, in log
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 22: ordinal not in range(128)
```

These methods need to be fixed so they don't blow up and at least log the problematic string/filename.

**Comment by Wesmania** [comment]
Does it still happen now that we're on py3?

**Comment by Wesmania** [comment]
I'll consider this abandoned.
