### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#689]
```
2017-03-28 17:37:03,635 INFO     root                           FAF version: 0.12.4+1578 Environment: production
2017-03-28 17:37:03,644 INFO     util                           PERSONAL_DIR initial: C:\Users\ÐÐ´Ð¼Ð¸Ð½\Documents
2017-03-28 17:37:03,645 ERROR    util                           PERSONAL_DIR not ok, falling back.
Traceback (most recent call last):
  File "src\util\__init__.py", line 103, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-13: ordinal not in range(128)
2017-03-28 17:37:03,647 INFO     util                           PERSONAL_DIR final: C:\ProgramData\FAForever\user
2017-03-28 17:37:03,953 INFO     __main__                       >>> --------------------------- Application Launch
2017-03-28 17:37:04,454 INFO     faf.secondaryServer.Statistic  Instantiating secondary server.
2017-03-28 17:37:04,469 INFO     util                           Read common stylesheet: client/client.css
2017-03-28 17:37:04,611 INFO     util                           Read common stylesheet: news/news_webview.css
2017-03-28 17:37:05,701 INFO     util                           Read common stylesheet: stats/formatters/style.css
2017-03-28 17:37:05,717 INFO     faf.secondaryServer.Tournament Instantiating secondary server.
2017-03-28 17:37:05,719 INFO     util                           Read common stylesheet: tournaments/formatters/style.css
2017-03-28 17:37:05,723 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "src/__main__.py", line 130, in <module>
  File "src/__main__.py", line 90, in runFAF
  File "src\client\_clientwindow.py", line 523, in setup
  File "src\vault\__init__.py", line 45, in __init__
  File "src\vault\__init__.py", line 66, in reloadView
UnicodeEncodeError: 'ascii' codec can't encode character u'\u044f' in position 0: ordinal not in range(128)
2017-03-28 17:37:06,674 INFO     news.wpapi                     Received http://direct.faforever.com/wp-json/wp/v2/posts?per_page=20&page=1&_embed=1
```

**Comment by duk3luk3** [comment]
And another one

```
Traceback (most recent call last):
  File "C:\Miniconda\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "src/__main__.py", line 130, in <module>
  File "src/__main__.py", line 90, in runFAF
  File "src\client\_clientwindow.py", line 504, in setup
  File "src\news\__init__.py", line 4, in <module>
  File "src\news\_newswidget.py", line 43, in <module>
  File "src\news\_newswidget.py", line 46, in NewsWidget
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 180892: ordinal not in range(128)
```

**Comment by Wesmania** [comment]
First char is 'я', I imagine somehow this character ended up in a username or password (these are loaded from the config file). Who gave you that first exception?

Second file can be changed by themes, it's the only way I imagine a non-ascii character could end up there. Maybe we can decode the files in util, or maybe warn that putting non-ascii in themes will break things. Again, who gave you this exception?

Maybe we can try and push for the move to python3, this would fix all our unicode troubles for good.

**Comment by duk3luk3** [comment]
> Maybe we can try and push for the move to python3, this would fix all our unicode troubles for good.

It would, after first pulling your hair out for 100 hours because there will be encoding/decoding failures everywhere :P

Python 3 makes it easy to write proper encoding handling from the start, but porting existing (bad) python2 code is horrible and I don't envy whoever will end up doing it ;)

> Again, who gave you this exception?

They're from the tech support forum:

http://forums.faforever.com/viewtopic.php?f=3&t=14268
http://forums.faforever.com/viewtopic.php?f=3&t=14282

**Comment by Wesmania** [comment]
It's weird that this first exception breaks after 180k characters - the file it's meant to load is tiny. I asked the guy on the forum to post it.

**Comment by duk3luk3** [comment]
Thanks :-)

**Comment by Wesmania** [comment]
Seems the first issue was indeed caused by non-ascii values either in password or in username, saved in the settings. Some weird code path could maybe save user input in the text field - I assume that a valid login must be ascii?

**Comment by duk3luk3** [comment]
> I assume that a valid login must be ascii?

No, why? :-) All I know is that usernames must be at least 3 chars long.

**Comment by Wesmania** [comment]
Username and password hash are used as GET arguments over here:
http://content.faforever.com/faf/vault/maps.php
Using password hash in a GET is bad enough in itself, but also means we have to encode the username and make sure the php script handles it properly. Fixing the url so the username / password bit is only used once we actually log in would also be nice.

**Comment by duk3luk3** [comment]
That's a legacy script that needs to be replaced using the api (https://github.com/FAForever/api/blob/develop/api/maps.py or the corresponding java-api endpoints).

We shouldn't worry about that other than not breaking it any worse than it is already broken until we're done replacing it.
