### ISSUE TITLE
Exception using matchmaker

### ISSUE THREAD

**Issue by muellni** [FAForever/client#780]
**I experienced...** this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fafclient/src/games/_gameswidget.py", line 166, in startSubRandomRankedSearch
    factionSubset[random.randint(0, l - 1)]))
  File "/usr/lib/python3.6/site-packages/fafclient/src/games/_gameswidget.py", line 260, in startSearchRanked
    self.client.search_ranked(faction=self.race.value)
  File "/usr/lib/python3.6/site-packages/fafclient/src/client/_clientwindow.py", line 1160, in search_ranked
    self.game_session.listen()
  File "/usr/lib/python3.6/site-packages/fafclient/src/fa/game_session.py", line 90, in listen
    assert self.state == GameSessionState.OFF
AssertionError
```

**how to reproduce** I clicked the matchmaker Play button with all factions selected. Then clicked on Seraphim to deselect. Search stopped, so I clicked the Play button again. This triggered the exception.
My version is `0.15.0`

**Comment by Wesmania** [comment]
I recall this issue existing in stable as well, I'm pretty sure I reproduced it there. I'll look at it once we have time to tackle all the code in the fa folder.
