### ISSUE TITLE
a bunch of errors in develop

### ISSUE THREAD

**Issue by faf5678** [FAForever/client#82]
happens when the game is launched.
first:
Traceback (most recent call last):
  File "src/__main__.py", line 48, in excepthook
    sys.excepthook = excepthook_original
NameError: global name 'excepthook_original' is not defined

second:
Original exception was:
Traceback (most recent call last):
  File "C:\fa\lobby\src\fa\replayserver.py", line 201, in acceptConnection
    self.recorders.append(ReplayRecorder(self, socket))
  File "C:\fa\lobby\src\fa\replayserver.py", line 63, in __init__
    if settings.value("fa.live_replay", DEFAULT_LIVE_REPLAY, type=bool):
NameError: global name 'settings' is not defined

**Comment by Sheeo** [comment]
This looks to be solved in current develop.
