### ISSUE TITLE
Rehost bug

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#828]
http://forums.faforever.com/viewtopic.php?p=153042#p153042

```
Traceback (most recent call last):
File "src\client\_clientwindow.py", line 1180, in request_launch
File "src\client\connection.py", line 259, in send
File "C:\Python36\lib\json\__init__.py", line 231, in dumps
File "C:\Python36\lib\json\encoder.py", line 199, in encode
File "C:\Python36\lib\json\encoder.py", line 257, in iterencode
File "C:\Python36\lib\json\encoder.py", line 180, in default
TypeError: Object of type 'GameVisibility' is not JSON serializable
```

**Comment by Wesmania** [comment]
I'm on it.
