### ISSUE TITLE
opening private chat window error

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#929]
when double clicking a username in the user list in aeolus throws an error when a private chat tab already is open

double click on a username in the user list while a private chat tab is already open

would be nice if the private chat tab would be in focus when doing that

FAF version: 0.16.1-rc.2+252 Environment: production
[log with error](https://github.com/FAForever/client/files/1580848/forever.zip)

```2017-12-21 23:29:37,818 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\chat\channel.py", line 370, in nickDoubleClicked
  File "src\chat\chatter.py", line 404, in doubleClicked
  File "src\chat\_chatwidget.py", line 213, in openQuery
UnboundLocalError: local variable 'priv_chan' referenced before assignment
2017-12-21 23:29:37,821 ERROR    __main__                       Runtime Info:```

**Comment by Wesmania** [comment]
Should be fixed by 33b53d975911.
